version: '2'
services:
    mysql:
        container_name: spring_bucks_mysql
        extends:
            file: mysql.yml
            service: mysql
    mongo:
        container_name: spring_bucks_mongo
        extends:
            file: mongo.yml
            service: mongo
    redis:
        container_name: spring_bucks_redis
        extends:
            file: redis.yml
            service: redis
