version: '2'
services:
    mongo:
        image: mongo:4.2.6
        volumes:
            - ./data/mongo/data:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
        ports:
            - 27017:27017
