server:
  port: 80
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
    gateway:
      discovery:
        locator:
          # ??????????????????? serviceId ?????????????? false??? true ?????????????? serviceId ????????
          enabled: true
  application:
    name: api-gateway
