version: "3"

services:
  mysql:
    image: mysql
    expose:
      - 3306
    environment:
      - MYSQL_DATABASE=spring_bucks
      - MYSQL_USER=springbucks
      - MYSQL_PASSWORD=springbucks
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 3306:3306

  redis:
    image: redis
    expose:
      - 6379
    ports:
      - 6379:6379

  consul:
    image: consul
    expose:
      - 8300
      - 8301
      - 8302
      - 8400
      - 8500
      - 8600
    ports:
      - 8500:8500

  rabbitmq:
    image: rabbitmq:3.7-management
    expose:
      - 5672
      - 15672
    ports:
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=spring
      - RABBITMQ_DEFAULT_PASS=spring

  zipkin:
    image: openzipkin/zipkin
    depends_on:
      - rabbitmq
    expose:
      - 9411
    ports:
      - 9411:9411
    links:
      - rabbitmq
    # Wait for rabbitmq - Can use wait-for-it instead.
    restart: always
    environment:
      - RABBIT_ADDRESSES=rabbitmq:5672 
      - RABBIT_USER=spring
      - RABBIT_PASSWORD=spring

  api-gateway:
    image: qxr777/api-gateway:1.0.0
    depends_on:
      - mysql
      - consul
      - rabbitmq
      - zipkin
      - redis
    links:
      - consul
    expose:
      - 80
    ports:
      - 80:80

  config-server:
    image: qxr777/config-server:1.0.0
    depends_on:
#      - mysql
      - consul
      - rabbitmq
#      - zipkin
#      - redis
    links:
      - consul
      - rabbitmq
    expose:
      - 8888
    ports:
      - 8888:8888

  waiter-service:
    image: qxr777/waiter-service:1.0.0
    restart: always
    depends_on:
      - mysql
      - consul
      - rabbitmq
      - zipkin
      - redis
      - config-server
    links:
      - mysql
      - consul
      - rabbitmq
      - zipkin
      - redis
    expose:
      - 8080
    ports:
      - 8080:8080

  barista-service:
    image: qxr777/barista-service:1.0.0
    depends_on:
      - mysql
      - consul
      - rabbitmq
      - zipkin
    links:
      - mysql
      - consul
      - rabbitmq
      - zipkin

  customer-service-8090:
    image: qxr777/customer-service:1.0.0
    depends_on:
      - waiter-service
    links:
      - consul
      - rabbitmq
      - zipkin
      - waiter-service
    expose:
      - 8090
    ports:
      - 8090:8090
    environment:
      - SERVER_PORT=8090

  customer-service-9090:
    image: qxr777/customer-service:1.0.0
    depends_on:
      - waiter-service
    links:
      - consul
      - rabbitmq
      - zipkin
      - waiter-service
    expose:
      - 9090
    ports:
      - 9090:9090
    environment:
      - SERVER_PORT=9090
