{
 "title": "Board Game Buddy",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Spring AI Client Seconds Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "spring_ai_chat_client_seconds_max",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spring AI Chat Client Active Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "spring_ai_chat_client_active_seconds_max",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vector Store Seconds Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "db_vector_client_operation_seconds_max",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vector Store Active Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "db_vector_client_operation_active_seconds_max",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GenAI Operation Seconds Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "gen_ai_client_operation_seconds_max",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Token Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "gen_ai_client_token_usage_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}